#!/bin/bash
set -e

function install_systemd_service() {
    echo "Installing socksd as a systemd service"

    echo '
[Unit]
Description=socksd service
After=network.target

[Service]
User=nobody
Type=simple
ExecStart=/usr/bin/socksd -i 0.0.0.0 -p 1337
Restart=on-failure

[Install]
WantedBy=multi-user.target
' > /usr/lib/systemd/system/socksd.service
    systemctl daemon-reload
    exit 0
}

function install_initd_service() {
    echo "Installing socksd as a init.d service"
    echo '#!/bin/sh
if [ -e /run/systemd/system ] ; then
    exit 0
fi

do_socksd() {
    case "$1" in
        start)
            /usr/bin/socksd -i 0.0.0.0 -p 1337
            ;;
	stop)
	    pkill -x socksd
	    ;;
        restart|reload|force-reload)
	    pkill -x socksd
	    /usr/bin/socksd -i 0.0.0.0 -p 1337
            ;;
        *)
            return 1
            ;;
    esac
}

do_socksd "$@"' > /etc/init.d/socksd
    chmod +x /etc/init.d/socksd
    exit 0
}

pidof /sbin/init && install_systemd_service || install_initd_service

exit 0
